name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: db_test
          POSTGRES_PASSWORD: postgres_password
          POSTGRES_PORT: 5432
          POSTGRES_USER: postgres_user
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:

      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install --yes postgresql-client

      - uses: actions/checkout@v2
      - name: Find schema
        run: cat schema.sql

#      - name: Start client
#        run: psql -h postgres -U postgres_user -d db_test
#       psql command works, but database server is not running
#      - name: Read schema
#        run: psql -f schema.sql -p 5432 -U posrtgres_user db_test
#        env:
#          PGPASSWORD: postgres_password
